### ISSUE TITLE
Warning in Network Settings when Network Activated

### ISSUE THREAD

**Issue by mrjarbenne** [RavanH/jetpack-module-control#2]
I'm seeing this on my development server when the plugin is network activated: 

Warning: Missing argument 1 for Jetpack_Module_Control::add_settings_section(), called in /srv/www/wpmu-subdomain/wp-content/plugins/jetpack-module-control/jetpack-module-control.php on line 569 and defined in /srv/www/wpmu-subdomain/wp-content/plugins/jetpack-module-control/jetpack-module-control.php on line 610

Great plugin. Nice work.

**Comment by RavanH** [comment]
Thanks @mrjarbenne the issue has been fixed https://github.com/RavanH/jetpack-module-control/pull/3 and will be released as version 1.2

**Comment by mrjarbenne** [comment]
Thanks.
