### ISSUE TITLE
Wishlist: Option to toggle Development Mode on Subsite Dashboard

### ISSUE THREAD

**Issue by mrjarbenne** [RavanH/jetpack-module-control#4]
I might be alone on this one, but in some circumstances having development mode turned on for the majority of subsites but being able to leverage a few .com services on others would be helpful. It would be greate to have access to toggle development mode off on a site by site basis, leaving it on for the majority of sites. 

Thought it wouldn't hurt to put it out there.

**Comment by RavanH** [comment]
Hi Jared, this is an excellent idea. It's noted on the todo list :)

Btx, thanks for the 5 stars on WordPress.org !

**Comment by mrjarbenne** [comment]
My pleasure. Thanks the considering the enhancement. Cheers.

**Comment by RavanH** [comment]
Hi mrjarbenne, the possibility to control plugin settings on a per-site basis (by Super Admin only at this point) has now been added to the development branch. If you'd like to test, you can download zips from https://github.com/RavanH/jetpack-module-control/releases/tag/1.4-alpha or https://wordpress.org/plugins/jetpack-module-control/developers/ (Development Version) ... 

Super Admin can override the network defaults on each site's Settings > General admin page. These options are not open for normal Admin users.

Please let me know if/how it works out for you ! Thanks :)

**Comment by mrjarbenne** [comment]
Sweet. Checking it out now.

**Comment by mrjarbenne** [comment]
I can't get the settings to stick on the subdomain. In this case, originally the Jetpack plugin was activated on the site (not network activated: not sure if that matters). I activated Jetpack network-wide, then went in to toggle on a per site basis.

The video shows what I'm referring to: 

http://www.screencast.com/t/jiq7nmL6A6tn

**Comment by RavanH** [comment]
OK, thanks for letting me know... excellent screencast btw :) 

Does after switching off the Dev Mode option (and it NOT reflecting that new status on the renewed admin page) the development mode actually get switched off? I mean, can you now go to Jetpack admin page and does it now propose to set up a connection?

**Comment by RavanH** [comment]
I've been able to reproduce the issue. Currently, you can leave the Network option "Development Mode" switched OFF while enabling the option on specific sub-sites. But not the other way around yet... Will work on that for the next dev version.

**Comment by mrjarbenne** [comment]
Sorry I didn't get back to this earlier today. I was thinking that I hadn't included that information: that the dev mode was switched on in the Network settings.

**Comment by RavanH** [comment]
Update: latest dev release https://downloads.wordpress.org/plugin/jetpack-module-control.zip should work now both when network Development Mode is on and off.

Please let me know the results if you care to test it. Your feedback is much appreciated! :)

**Comment by mrjarbenne** [comment]
With this latest version, and Jetpack 3.7.2, I'm seeing this error:

Warning: Invalid argument supplied for foreach() in /var/www/commons.hwdsb.on.ca/wordpress/wp-content/plugins/jetpack/class.jetpack.php on line 2527 

It's appearing in the logs when both plugins are network activated, but when the Control Module plugin is Network Activated, but Jetpack is activated on a site-by-site basis, the error also appears in the header area of sub-site dashboards.

Hope this helps.

**Comment by RavanH** [comment]
Great catch! I missed that, thanks. 

Should be fixed in the latest https://downloads.wordpress.org/plugin/jetpack-module-control.zip (version 1.4-alpha-6)
