### ISSUE TITLE
Split options into 2 rows

### ISSUE THREAD

**Issue by cfoellmann** [RavanH/jetpack-module-control#9]
How about splitting all options into 2 rows?

Offline | connection-required

and/or grey out all options requiring .com connection if dev mode is active/enforced.

**Comment by RavanH** [comment]
Not a bad idea. The list is growing fast so some kind of solution will be needed...

I'll consider this at the same time  as I implement new icons for all the new modules :)

**Comment by cfoellmann** [comment]
I could contribute a little if you like.
You could start by adding your wishlist as issues here on GH and I will see what I can do and like.
And the ideas throughout the codebase 😉
